/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "place" */
export const placeFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_properties",


	"get_author_rank",
	"get_local_snapshots",
	"get_placement_author",
	"get_placements_at",
	"get_publishers_at",
	"get_snapshot_at",
	"place_pixel",
	"place_pixel_at",
	"publish_next_snapshot_at",
	"publish_starting_snapshot",
	"publish_same_snapshot_upto",];


/** Generate tuple array of function names with given zomeName */
export function generatePlaceZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of placeFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zPlace" */
export const placeZomeFunctions: [ZomeName, FunctionName][] = generatePlaceZomeFunctionsArray("zPlace");
