/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "placeDashboard" */
export const placeDashboardFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_properties",
	"create_game",
	"list_all_games",
	"list_my_games",];


/** Generate tuple array of function names with given zomeName */
export function generatePlaceDashboardZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of placeDashboardFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zPlaceDashboard" */
export const placeDashboardZomeFunctions: [ZomeName, FunctionName][] = generatePlaceDashboardZomeFunctionsArray("zPlaceDashboard");
