/* This file is generated by zits. Do not edit manually */

import {
/** Types */
HoloHash,
AgentPubKey,
DnaHash,
WasmHash,
EntryHash,
ActionHash,
AnyDhtHash,
KitsuneAgent,
KitsuneSpace,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleId,
InstalledCell,
Timestamp,
HoloHashed,
/** Action */
SignedActionHashed,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** Capabilities */
CapSecret,
CapClaim,
ZomeCallCapGrant,
CapAccess,
CapGrant,
/** CounterSigning */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** DhtOps */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** Entry */
EntryVisibility,
AppEntryType,
EntryType,
EntryContent,
Entry,
/** Record */
Record,
RecordEntry,
/** admin types */
ZomeName,
MembraneProof,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioning,
HoloHashB64,
DnaVersionSpec,
DnaVersionFlexible,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';

import {
// Common
Dictionary,
EntryHashB64,
ActionHashB64,
DhtOpHashB64,
DnaHashB64,
AgentPubKeyB64,
AnyDhtHashB64,
DhtOpHash,
// DnaFile
DnaFile,
DnaDef,
Zomes,
WasmCode,
// entry-details
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
// Validation
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

export interface GetAuthorRankInput {
  author: AgentPubKeyB64
  bucketIndex: number
}

export interface GetPlacementAuthorInput {
  placement: number
  bucketIndex: number
}

/** DEBUGGING API */
export interface PlaceAtInput {
  placement: DestructuredPlacement
  bucketIndex: number
}

export interface BucketRangeInput {
  latestKnownBucket: number
  nowBucket: number
}

export type DoublePixel = number;

export enum PlaceEntryType {
	Placement = 'Placement',
	Snapshot = 'Snapshot',
}
export type PlaceEntryVariantPlacement = {placement: Placement}
export type PlaceEntryVariantSnapshot = {snapshot: Snapshot}
export type PlaceEntry = 
 | PlaceEntryVariantPlacement | PlaceEntryVariantSnapshot;

export interface DestructuredPlacement {
  x: number
  y: number
  colorIndex: number
}

/** A Public Entry representing a pixel placement by an agent */
export interface Placement {
  pixel: number
}

/** Dna properties */
export interface PlaceProperties {
  startTime: number
  canvasSize: number
  bucketSizeSec: number
  pixelsPerBucket: number
  snapshotIntervalInBuckets: number
}

/** A Public Entry representing the whole canvas for a specific time bucket */
export interface Snapshot {
  imageData: Uint8Array
  timeBucketIndex: number
}
