/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {Days, MAX_BUCKET_SIZE_SEC, MIN_BUCKET_SIZE_SEC, PlaceEntry, BucketRangeInput, DestructuredPlacement, DoublePixel, GetAuthorRankInput, GetPlacementAuthorInput, PlaceAtInput, PlaceProperties, Placement, Snapshot, } from './place.types';
// @ts-ignore
import {
// @ts-ignore
WebsocketConnectionOptions, KitsuneAgent, KitsuneSpace, HoloHashB64, AgentPubKeyB64, DnaHashB64, WasmHashB64, EntryHashB64, ActionHashB64, AnyDhtHashB64, InstalledAppId, Signature, CellId, DnaProperties, RoleName, InstalledCell, Timestamp, Duration, HoloHashed, NetworkInfo, FetchPoolInfo,
/** hdk/action.ts */
// @ts-ignore
SignedActionHashed, RegisterAgentActivity, ActionHashed, ActionType, Action, NewEntryAction, Dna, AgentValidationPkg, InitZomesComplete, CreateLink, DeleteLink, OpenChain, CloseChain, Update, Delete, Create,
/** hdk/capabilities.ts */
// @ts-ignore
CapSecret, CapClaim, GrantedFunctionsType, GrantedFunctions, ZomeCallCapGrant, CapAccessType, CapAccess, CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
// @ts-ignore
DhtOpType, DhtOp, getDhtOpType, getDhtOpAction, getDhtOpEntry, getDhtOpSignature,
/** hdk/entry.ts */
// @ts-ignore
EntryVisibility, AppEntryDef, EntryType, EntryContent, Entry,
/** hdk/record.ts */
// @ts-ignore
Record as HcRecord, RecordEntry as HcRecordEntry,
/** hdk/link.ts */
//AnyLinkableHash,
// @ts-ignore
ZomeIndex, LinkType, LinkTag, RateWeight, RateBucketId, RateUnits, Link,
/** api/admin/types.ts */
// @ts-ignore
InstalledAppInfoStatus, DeactivationReason, DisabledAppReason, StemCell, ProvisionedCell, ClonedCell, CellType, CellInfo, AppInfo, MembraneProof, FunctionName, ZomeName, ZomeDefinition, IntegrityZome, CoordinatorZome, DnaDefinition, ResourceBytes, ResourceMap, CellProvisioningStrategy, CellProvisioning, DnaVersionSpec, DnaVersionFlexible, AppRoleDnaManifest, AppRoleManifest, AppManifest, AppBundle, AppBundleSource, NetworkSeed, ZomeLocation,
} from '@holochain/client';


/// Simple Hashes
// @ts-ignore
type AgentArray = Uint8Array;
// @ts-ignore
type DnaArray = Uint8Array;
// @ts-ignore
type WasmArray = Uint8Array;
// @ts-ignore
type EntryArray = Uint8Array;
// @ts-ignore
type ActionArray = Uint8Array;
// @ts-ignore
type AnyDhtArray = Uint8Array;
// @ts-ignore
type AnyLinkableArray = Uint8Array;
// @ts-ignore
type ExternalArray = Uint8Array;

// @ts-ignore
import {
/** Common */
// @ts-ignore
DhtOpHashB64, DhtOpHash,
/** DnaFile */
// @ts-ignore
DnaFile, DnaDef, Zomes, WasmCode,
/** entry-details */
// @ts-ignore
EntryDetails, RecordDetails, Details, DetailsType, EntryDhtStatus,
/** Validation */
// @ts-ignore
ValidationStatus, ValidationReceipt,
} from '@holochain-open-dev/core-types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {placeFunctionNames} from './place.fn';
import {PlaceUnitEnum, PlaceLinkType} from './place.integrity';

/**
 *
 */
export class PlaceProxy extends ZomeProxy {
  static override readonly DEFAULT_ZOME_NAME = "zPlace";
  static override readonly FN_NAMES = placeFunctionNames;
  static override readonly ENTRY_TYPES = Object.values(PlaceUnitEnum);
  static override readonly LINK_TYPES = Object.values(PlaceLinkType);
 
  async getProperties(): Promise<PlaceProperties> {
    return this.call('get_properties', null);
  }

  async getAuthorRank(input: GetAuthorRankInput): Promise<number> {
    return this.call('get_author_rank', input);
  }

  async getLocalSnapshots(): Promise<number[]> {
    return this.call('get_local_snapshots', null);
  }

  async getPlacementAuthor(input: GetPlacementAuthorInput): Promise<AgentPubKeyB64 | null> {
    return this.call('get_placement_author', input);
  }

  async getPlacementsAt(timeBucketIndex: number): Promise<Placement[]> {
    return this.call('get_placements_at', timeBucketIndex);
  }

  async getPublishersAt(timeBucketIndex: number): Promise<AgentPubKeyB64[]> {
    return this.call('get_publishers_at', timeBucketIndex);
  }

  async getSnapshotAt(bucketIndex: number): Promise<Snapshot | null> {
    return this.call('get_snapshot_at', bucketIndex);
  }

  async placePixel(input: DestructuredPlacement): Promise<ActionArray> {
    return this.call('place_pixel', input);
  }

  async placePixelAt(input: PlaceAtInput): Promise<ActionArray> {
    return this.call('place_pixel_at', input);
  }

  async publishNextSnapshotAt(currentBucket: number): Promise<ActionArray | null> {
    return this.call('publish_next_snapshot_at', currentBucket);
  }

  async publishStartingSnapshot(): Promise<Snapshot> {
    return this.call('publish_starting_snapshot', null);
  }

  async publishSameSnapshotUpto(input: BucketRangeInput): Promise<ActionArray[]> {
    return this.call('publish_same_snapshot_upto', input);
  }
}
