[package]
name = "place_model"
version = "0.0.1"
edition = "2021"

[lib]
name = "place_model"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = { version = "1.0", default-features = false }

holochain_deterministic_integrity = { version = "0.0.10", default-features = false }
