[package]
name = "place_model"
version = "0.0.1"
edition = "2021"

[lib]
name = "place_model"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
#chrono = "=0.4.6"
serde = { version = "1.0", default-features = false }
hdi = { version = "0.0.19", default-features = false }
