name: build-webhapps

on:
  workflow_call:

jobs:
  build-webhapps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install hc tool
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run ci:hc-install
      # Install Hash Zome
      - name: Install Hash Zome
        run: |
          npm run install:hash-zome
      # build dna
      - name: Build DNA
        run: |
          npm run build:happ
      # Hash Zome
      - name: Hash Zome
        run: |
          npm run hash-zome
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install
      # Build webapp
      - name: Build webapp
        run: |
          npm run prepare-test
      # Package web-happ
      - name: Package web-happ
        run: |
          npm run dist:webhapp
      # build we-applet
      - name: build we-applet
        shell: bash
        run: |
          npm run build:we
      # Package we-applet
      - name: Package we-applet
        shell: bash
        run: |
          npm run dist:we
      # Regroup artifacts
      - name: Regroup artifacts
        run: |
          mkdir artifacts
          cp electron/bin/model_zome_hash.txt ./artifacts          
          cp target/wasm32-unknown-unknown/release/place_model.wasm ./artifacts
          cp target/wasm32-unknown-unknown/release/place.wasm ./artifacts
      # Display structure of uploaded files
      - name: Display structure of uploaded files
        run: ls -R
        working-directory: ./artifacts
      # "upload" artifacts
      - uses: actions/upload-artifact@master
        with:
          name: all-happ-artifact
          path: artifacts/
