name: build-dna

on:
  workflow_call:

jobs:
  build-dna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install hc tool
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run ci:hc-install
      # Install Hash Zome
      - name: Install Hash Zome
        run: |
          npm run install:hash-zome
      # build dna
      - name: Build DNA
        run: |
          npm run build:happ
      # Hash Zome
      - name: Hash Zome
        run: |
          npm run hash-zome
      # "upload" dna build artifacts
      - uses: actions/upload-artifact@master
        with:
          name: place-happ-artifact
          path: dna/workdir/place.happ
      - uses: actions/upload-artifact@master
        with:
          name: place-hash-artifact
          path: dna/workdir/place_zome_hash.txt
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install place --ignore-scripts
      # Build webapp
      - name: Build webapp
        run: |
          npm run prepare-test
      # Package web-happ
      - name: Package web-happ
        run: |
          npm run dist:webhapp
      # Regroup artifacts
      - name: Regroup artifacts
        run: |
          mkdir artifacts
          cp target/wasm32-unknown-unknown/release/place_model.wasm ./artifacts
          cp target/wasm32-unknown-unknown/release/place.wasm ./artifacts
          cp dna/workdir/place.dna ./artifacts
          cp dna/workdir/place.happ ./artifacts                   
          cp webapp/webhapp.workdir/place.webhapp ./artifacts
          cp electron/bin/model_zome_hash.txt ./artifacts
      # Display structure of uploaded files
      - name: Display structure of uploaded files
        run: ls -R
        working-directory: ./artifacts
      # "upload" artifacts
      - uses: actions/upload-artifact@master
        with:
          name: all-happ-artifact
          path: artifacts/
