name: build-dna

on:
  workflow_call:

jobs:
  build-dna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install hc tool
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run ci:hc-install
      # build dna
      - name: Build DNA
        run: |
          npm run build:happ
      # Install Hash Zome
      - name: Install Hash Zome
        run: |
          npm run install:hash-zome
      # Hash Zome
      - name: Hash Zome
        run: |
          npm run hash-zome
      # "upload" dna build artifacts
      - uses: actions/upload-artifact@master
        with:
          name: place-happ-artifact
          path: dna/workdir/place.happ
      - uses: actions/upload-artifact@master
        with:
          name: place-hash-artifact
          path: dna/workdir/place_zome_hash.txt
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install place --ignore-scripts
      # Build webapp
      - name: Build webapp
        run: |
          npm run prepare-test
      # Package web-happ
      - name: Package web-happ
        run: |
          npm run dist:webhapp
      # "upload" happ as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: happ-artifact
          path: dna/workdir/place.happ
      # "upload" web-happ as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: webhapp-artifact
          path: webapp/webhapp.workdir/place.webhapp
      # "upload" zome_hash as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: model-hash-artifact
          path: electron/bin/model_zome_hash.txt
