name: test-workflow x64

on: workflow_dispatch

env:
  PLACE_VERSION: 0.1.0-hc.165
  USE_HARD_LINKS: false

jobs:
  # Build the dna & happ
  call-build-dna:
    uses: ./.github/workflows/build-dna.yml

  # upload the app package for each target os
  build-binaries:
    needs: call-build-dna
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      # Check if exist
      #- name: tsc
      #   continue-on-error: true
      #  run: |
      #     tsc --version
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@master
        with:
          name: all-happ-artifact
      # Display structure of downloaded files
      - name: Display structure of downloaded files
        run: ls
        working-directory: ./
      # Dispatch artifacts
      - name: Dispatch artifacts
        run: |
          cp ./place.happ ./electron/bin
          cp ./model_zome_hash.txt ./electron/bin
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install
      # build webcomponents
      - name: build webcomponents
        shell: bash
        run: |
          npm run build:webcomponents
      # build webapp
      - name: build webapp
        shell: bash
        run: |
          npm run build:webapp
      # build electron
      - name: build electron
        shell: bash
        run: |
          npm run build -w electron
      # Package electron
      - name: Package electron
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist:build -w electron
#      # Build tar.gz
#      - name: Build tar.gz
#        if: ${{ runner.os == 'Linux' }}
#        continue-on-error: true
#        shell: bash
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          npm run dist-linux
#          gh release upload "manual-release" "electron/out/place-$PLACE_VERSION.tar.gz" --clobber
      # Check electron output folder
      - name: Check electron output folder
        continue-on-error: true
        run: ls -R
        working-directory: electron/out-builder
      # Build chaperone app
      - name: Build chaperone app (ubuntu only)
        continue-on-error: true
        if: ${{ runner.os == 'Linux' }}
        run: |
          npm run build:chaperone-mainnet
      # Check workdir folder
      - name: Check workdir folder
        continue-on-error: true
        run: ls -R
        working-directory: dna/workdir
#      #
#      - name: list releases
#        continue-on-error: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          gh release list
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "electron/out-builder/Place-$PLACE_VERSION.AppImage" --clobber
          gh release upload "manual-release" "webapp-chaperone/ui-chaperone.zip" --clobber
          gh release upload "manual-release" "we-applet/webhapp.workdir/place_we-applet.webhapp" --clobber          
          gh release upload "manual-release" "./place.webhapp" --clobber
          gh release upload "manual-release" "./place.happ" --clobber
          gh release upload "manual-release" "./place.dna" --clobber
          gh release upload "manual-release" "./place.wasm" --clobber
          gh release upload "manual-release" "./place_model.wasm" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "electron/out-builder/Place-$PLACE_VERSION.dmg" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete-asset "manual-release" "Place.Setup.$env:PLACE_VERSION.exe" -y          
          gh release upload "manual-release" "electron/out-builder/Place Setup $env:PLACE_VERSION.exe" --clobber
