name: test-workflow x64

on: workflow_dispatch

env:
  PLACE_VERSION: 0.0.1
  USE_HARD_LINKS: false

jobs:
  # Build the dna & happ
  call-build-dna:
    uses: ./.github/workflows/build-dna.yml

  # upload the app package for each target os
  build-binaries:
    needs: call-build-dna
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      # Check if exist
      #- name: tsc
      #   continue-on-error: true
      #  run: |
      #     tsc --version
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@master
        with:
          name: place-happ-artifact
          path: workdir
      - uses: actions/download-artifact@master
        with:
          name: place-webapp-artifact
          path: workdir
      - uses: actions/download-artifact@master
        with:
          name: place-hash-artifact
          path: electron/binaries
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install
      # Build happ
      - name: Build happ
        run: |
          npm run build
      # Build installers and binaries
      - name: Build binaries
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist
#      # Build tar.gz
#      - name: Build tar.gz
#        if: ${{ runner.os == 'Linux' }}
#        continue-on-error: true
#        shell: bash
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          npm run dist-linux
#          gh release upload "manual-release" "electron/out/place-$PLACE_VERSION.tar.gz" --clobber
      # Check electron output folder
      - name: Check electron output folder
        continue-on-error: true
        run: ls -R
        working-directory: electron/out
      # Build chaperone app
      - name: Build chaperone app (ubuntu only)
        continue-on-error: true
        if: ${{ runner.os == 'Linux' }}
        run: |
          npm run build:chaperone
      # Check workdir folder
      - name: Check workdir folder
        continue-on-error: true
        run: ls -R
        working-directory: workdir
#      #
#      - name: list releases
#        continue-on-error: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          gh release list
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "electron/out/Place-$PLACE_VERSION.AppImage" --clobber
          gh release upload "manual-release" "workdir/place.happ" --clobber
          gh release upload "manual-release" "workdir/place.webhapp" --clobber
          gh release upload "manual-release" "workdir/ui-chaperone.zip" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "electron/out/Place-$PLACE_VERSION.dmg" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "electron/out/Place Setup $env:PLACE_VERSION.exe" --clobber
